pedido1 =(2010,"3 sorvetes de baunilha", 25.50)
pedido2 = ( 456, "frango grelhado e um suco de laranja", 56.00)
pedido3 = (235, "risoto", 52.00)

print("Detalhes do pedido 1:")
print("número do pedido:", pedido1[0])
print(" itens: ", pedido1[1])
print("preço: ", pedido1[2])
print()

print("Detalhes do pedido 2:")
print("número do pedido:", pedido2[0])
print(" itens:", pedido2[1])
print("preço:", pedido2[2])
print()

print("Detalhes do pedido 3:")
print("número do pedido:", pedido3[0])
print(" itens: :", pedido3[1])
print("preço:", pedido3[2])
print()